version: '3'

services:
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  app-store:
  db-store:
